### ISSUE TITLE
Make graph object IDs display in graph components

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#212] opened 2023-08-03 10:29 UTC

**Comment by kallewesterling** [comment] 2023-10-12 10:32
Unclear in requirements
- instead of names, they should be numbered?

**Comment by kallewesterling** [comment] 2023-11-06 13:15
@chrisdburr Can you help us specify why this was a requested feature?

**Comment by chrisdburr** [comment] 2023-11-07 12:37
Having an ID for each of the assurance case elements would help users reference specific claims and would bring us closer into alignment with the GSN standard.

<img width="709" alt="Screenshot 2023-11-07 at 12 35 11" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/a1ed8303-49f6-403c-8dec-9286a32bfad0">

**Comment by kallewesterling** [comment] 2023-11-22 16:31
This issue seems like a duplicate of #296 to me, can you please sense-check that @chrisdburr ?

**Comment by chrisdburr** [comment] 2023-11-24 12:12
You are right, @kallewesterling. This is now a duplicate. Will close.

**Closed by chrisdburr** 2023-11-24 12:12 UTC
Labels: enhancement
