### ISSUE TITLE
[User Story]: Standardised and Immutable Identifier Assignment for Assurance Case Elements

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#438] opened 2024-05-08 09:47 UTC
### Role

As an assurance case editor

### Desired Feature

I want each element in the assurance case to have a unique identifier that is automatically assigned and formatted correctly according to a defined pattern

### Benefit

So that I can easily reference and maintain the structural integrity of the assurance case elements without error or inconsistency

### Acceptance Criteria

GIVEN I am adding a new property claim to an existing parent claim,
WHEN the new property claim is created,
THEN it should automatically receive a unique identifier that is a continuation of the parent's identifier (e.g., if the parent is P1, the child should be P1.1).
AND these identifiers should not be editable by the user to ensure consistency across the platform.

### Dependencies

- [ ] Develop a backend logic to programmatically assign and manage identifiers based on the existing assurance case structure.

### Technical Notes

- The system should follow a standardized naming convention similar to P[number].[subnumber] as used in established safety case frameworks.
- The UI should clearly display these identifiers next to the respective assurance case elements.
- Ensure that identifier generation and display are accessible, with adequate color contrast and text size according to WCAG 2.1 guidelines.

### Definition of Done

- [X] The feature fulfills all acceptance criteria.
- [X] The code is reviewed and meets team coding standards.
- [X] All unit, integration, and end-to-end tests are passed.
- [X] The feature meets accessibility standards set for the project.
- [X] The code passes the CI/CD pipeline quality controls (style and linting).
- [X] The feature is merged into the main branch.
- [X] The feature is deployed and functional in the QA environment.
- [X] The feature was demonstrated to the team and accepted by the product owner.

**Comment by kallewesterling** [comment] 2024-06-05 13:45
@chrisdburr @cptanalatriste Can you both remind me what our conversation was here, in our 2h get-together in the office? I'm pretty sure we discussed this as part of your work on the schema, @cptanalatriste so perhaps this issue is no longer interesting/valid?

**Comment by kallewesterling** [comment] 2024-06-05 16:49
@chrisdburr Can you check/edit the acceptance criteria here, according to the conversation today?

**Comment by chrisdburr** [comment] 2024-06-06 09:47
Few additional details that may help:

## Goal Claim

- Only ever one, so always `G1`

## Strategy Claims

- Always sequential numbering for first-level strategy elements (e.g. `S1`, `S2`, ... `SN`)

## Property Claims

- Always sequential numbering for first-level claims (e.g. `P1`, `P2`, ... `PN`)
- Second-level claims inherit numbering of parents (e.g. `P1` --> `P1.1`, `P1.2`; `P2.1` --> `P2.1.1`, `P.2.1.2`)
- N-level claims do not increase sequentially, but are constrained by their parent.
  - Example: There may be a `P1.1` and a `P3.1` without there being a `P2.1` in the case where `P2` has no children.
  
# Evidence

- Always sequential numbering for evidence elements (e.g. `E1`, `E2`, ... `EN`)
- No `E1.1` can exist, because evidence elements cannot be nested.
- Evidence does not inherit numbering of parents because evidence may be linked to multiple property claims.

**Comment by chrisdburr** [comment] 2024-06-06 09:48
@cptanalatriste: you may want to consider whether these rules are enforced in the schema.

**Comment by cptanalatriste** [comment] 2024-06-12 13:39
@RichGriff you should be able to pass the current names you're using, and they will get corrected at the backend. I will try I the following days to remove the name enforcement, and assign it at insert time.

**Comment by RichGriff** [comment] 2024-06-12 13:44
@cptanalatriste  
I tried this first and it still had my set names on it. 

If I already have an instance of the server installed locally, will I have to create a new migration for your changes to be applied? The doc steps had a migration command but that said no changes.

**Comment by RichGriff** [comment] 2024-06-13 17:34
After a few discussions today we are in a good position with the Identifiers working as intended 🚀 

Just need @cptanalatriste to look at the `Evidence` Identifiers

**Comment by RichGriff** [comment] 2024-06-20 16:04
Verified with Rich and Carlos on a development call

This is now in staging already

**Comment by chrisdburr** [comment] 2024-06-25 14:11
Closing.

**Closed by chrisdburr** 2024-06-25 14:11 UTC
